export const contraception = [
  {
    Category2: 'IUD',
    Date: null,
    'Date start': '30-Jun-20',
    'Date end': '30-Dec-20',
    'Date inactive': null,
    'Name of method': 'IUD',
    'Status 1': 'UKMEC (init) 1',
    'Status 2': 'UKMEC (cont) 1',
    'Timeline static': null,
    'Episode static': null,
    'Status hover': null,
    'Clinical details':
      'Abdo pain, IUD removed after 6 months. Immediate switch to CHC patch.',
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Griffiths',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Category2: 'IUS',
    Date: null,
    'Date start': null,
    'Date end': null,
    'Date inactive': null,
    'Name of method': 'IUS',
    'Status 1': 'UKMEC (init) 1',
    'Status 2': 'UKMEC (cont) 1',
    'Timeline static': null,
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: null,
    'Clinic location': null,
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Category2: 'Implant',
    Date: null,
    'Date start': '30-Jun-22',
    'Date end': 'ongoing',
    'Date inactive': '30-Jun-25',
    'Name of method': 'IMP',
    'Status 1': 'UKMEC (init) 1',
    'Status 2': 'UKMEC (cont) 1',
    'Timeline static': null,
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Matron Collins',
    'Clinic location': 'Dartmoor clinic',
    Brand: 'Nexplanon',
    Dose: 'One',
    Site: 'Left arm SC',
    'Batch number': 'FSR4323XG',
    'Expiry date': 'Aug-27',
  },
  {
    Category2: 'Injectables',
    Date: null,
    'Date start': null,
    'Date end': null,
    'Date inactive': null,
    'Name of method': 'Depo',
    'Status 1': 'UKMEC (init) 1',
    'Status 2': 'UKMEC (cont) 1',
    'Timeline static': null,
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: null,
    'Clinic location': null,
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Category2: 'Injectables',
    Date: null,
    'Date start': null,
    'Date end': null,
    'Date inactive': null,
    'Name of method': 'Sayana',
    'Status 1': 'UKMEC (init) 1',
    'Status 2': 'UKMEC (cont) 1',
    'Timeline static': null,
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: null,
    'Clinic location': null,
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Category2: 'Progesterone-only pill',
    Date: null,
    'Date start': null,
    'Date end': null,
    'Date inactive': null,
    'Name of method': 'POP',
    'Status 1': 'UKMEC (init) 1',
    'Status 2': 'UKMEC (cont) 1',
    'Timeline static': null,
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: null,
    'Clinic location': null,
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Category2: 'Combined Hormonal Contraception',
    Date: null,
    'Date start': '1-Sep-22',
    'Date end': 'ongoing',
    'Date inactive': null,
    'Name of method': 'COC',
    'Status 1': 'UKMEC (init) 2',
    'Status 2': 'UKMEC (cont) 3',
    'Timeline static': null,
    'Episode static': null,
    'Status hover': 'Migraine without aura ',
    'Clinical details': 'Spotting after 4 months on IUS, COC added 01-Sep-22',
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Griffiths',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Category2: 'Combined Hormonal Contraception',
    Date: null,
    'Date start': '31-Dec-20',
    'Date end': '4-Jul-21',
    'Date inactive': null,
    'Name of method': 'Patch',
    'Status 1': 'UKMEC (init) 2',
    'Status 2': 'UKMEC (cont) 3',
    'Timeline static': null,
    'Episode static': null,
    'Status hover': 'Migraine without aura ',
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Griffiths',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Category2: 'Combined Hormonal Contraception',
    Date: null,
    'Date start': null,
    'Date end': null,
    'Date inactive': null,
    'Name of method': 'Ring',
    'Status 1': 'UKMEC (init) 2',
    'Status 2': 'UKMEC (cont) 3',
    'Timeline static': null,
    'Episode static': null,
    'Status hover': 'Migraine without aura ',
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: null,
    'Clinic location': null,
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Category2: null,
    Date: null,
    'Date start': null,
    'Date end': null,
    'Date inactive': null,
    'Name of method': 'LNG',
    'Status 1': 'UKMEC (init) 1',
    'Status 2': 'UKMEC (cont) 1',
    'Timeline static': null,
    'Episode static': '[no. of LNG events to date]',
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: null,
    'Clinic location': null,
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Category2: 'Emergency Contraception',
    Date: '4-Feb-20',
    'Date start': null,
    'Date end': null,
    'Date inactive': null,
    'Name of method': 'UPA',
    'Status 1': 'UKMEC (init) 1',
    'Status 2': 'UKMEC (cont) 1',
    'Timeline static': null,
    'Episode static': '[no. of UPA events to date]',
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Nurse Cole',
    'Clinic location': 'Dartmoor clinic',
    Brand: 'EllaOne',
    Dose: '30mg',
    Site: 'PO',
    'Batch number': '234343FG',
    'Expiry date': 'Feb-23',
  },
  {
    Category2: 'Emergency Contraception',
    Date: '12-Dec-21',
    'Date start': null,
    'Date end': null,
    'Date inactive': null,
    'Name of method': 'UPA',
    'Status 1': 'UKMEC (init) 1',
    'Status 2': 'UKMEC (cont) 1',
    'Timeline static': null,
    'Episode static': '[no. of UPA events to date]',
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Matron Collins',
    'Clinic location': 'Main clinic',
    Brand: 'EllaOne',
    Dose: '30mg',
    Site: 'PO',
    'Batch number': '654432FG',
    'Expiry date': 'Feb-23',
  },
  {
    Category2: 'Emergency Contraception',
    Date: '1-May-22',
    'Date start': null,
    'Date end': null,
    'Date inactive': null,
    'Name of method': 'UPA',
    'Status 1': 'UKMEC (init) 1',
    'Status 2': 'UKMEC (cont) 1',
    'Timeline static': null,
    'Episode static': '[no. of UPA events to date]',
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Matron Collins',
    'Clinic location': 'Dartmoor clinic',
    Brand: 'EllaOne',
    Dose: '30mg',
    Site: 'PO',
    'Batch number': '432324HT',
    'Expiry date': 'Mar-24',
  },
  {
    Category2: 'Termination of Pregnancy',
    Date: '2-Feb-22',
    'Date start': null,
    'Date end': null,
    'Date inactive': null,
    'Name of method': 'mTOP',
    'Status 1': 'No complication',
    'Status 2': null,
    'Timeline static': null,
    'Episode static': '[no. of mTOP events to date]',
    'Status hover': null,
    'Clinical details': 'Home is within 45 minutes. ',
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Griffiths',
    'Clinic location': 'Main clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Category2: 'Termination of Pregnancy',
    Date: null,
    'Date start': null,
    'Date end': null,
    'Date inactive': null,
    'Name of method': 'sTOP',
    'Status 1': 'No complication',
    'Status 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Griffiths',
    'Clinic location': 'Main clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
];
