export const fullData = [
  {
    Section: 'STIs',
    Category2: 'In-clinic tests',
    Category: 'In-clinic',
    'Name of test': 'Urine dip',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'In-clinic tests',
    Category: 'In-clinic',
    'Name of test': 'Preg',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'In-clinic tests',
    Category: 'In-clinic',
    'Name of test': 'Microscopy',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'In-clinic tests',
    Category: 'In-clinic',
    'Name of test': 'TV Ag',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'Non-STI MC&S',
    Category: 'MC&S',
    'Name of test': 'Urine MC&S',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'Non-STI MC&S',
    Category: 'MC&S',
    'Name of test': 'HVS MC&S',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Throat',
    'Name of test': 'Throat CT NAAT',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Throat',
    'Name of test': 'Throat GC NAAT',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Throat',
    'Name of test': 'Throat MGen NAAT',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Throat',
    'Name of test': 'Throat LGV NAAT',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Throat',
    'Name of test': 'Throat GC Culture',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Throat',
    'Name of test': 'Throat MGen geno',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Throat',
    'Name of test': 'Throat Syphilis swab',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Rectal',
    'Name of test': 'Rectal CT NAAT',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Rectal',
    'Name of test': 'Rectal GC NAAT',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Rectal',
    'Name of test': 'Rectal MGen NAAT',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Rectal',
    'Name of test': 'Rectal HSV swab',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Rectal',
    'Name of test': 'Rectal MPV swab',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Rectal',
    'Name of test': 'Rectal LGV NAAT',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Rectal',
    'Name of test': 'Rectal GC Culture',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Rectal',
    'Name of test': 'Rectal MGen geno',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Rectal',
    'Name of test': 'Rectal Syphilis swab',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Uro-genital',
    'Name of test': 'Uro-genital CT NAAT',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Uro-genital',
    'Name of test': 'Uro-genital GC NAAT',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Uro-genital',
    'Name of test': 'Uro-genital MGen NAAT',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Uro-genital',
    'Name of test': 'Uro-genital HSV swab',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Uro-genital',
    'Name of test': 'Uro-genital MPV swab',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Uro-genital',
    'Name of test': 'Uro-genital LGV NAAT',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Uro-genital',
    'Name of test': 'Uro-genital GC Culture',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Uro-genital',
    'Name of test': 'Uro-genital MGen geno',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Uro-genital',
    'Name of test': 'Uro-genital Syphilis swab',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'STIs',
    Category: 'Uro-genital',
    'Name of test': 'Uro-genital MPV urine',
    Row: 2,
  },
  {
    Section: 'STIs',
    Category2: 'Ulcer swabs',
    Category: 'Throat',
    'Name of test': 'Throat HSV swab',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'Ulcer swabs',
    Category: 'Throat',
    'Name of test': 'Throat MPV swab',
    Row: 1,
  },
  {
    Section: 'STIs',
    Category2: 'Other',
    Category: 'Other',
    'Name of test': 'Other',
    Row: 1,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HIV',
    'Name of test': 'POCT',
    Row: 1,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HIV',
    'Name of test': 'HIV-1',
    Row: 1,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HIV',
    'Name of test': 'HIV-2',
    Row: 1,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HIV',
    'Name of test': 'p24 Ag',
    Row: 2,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HIV',
    'Name of test': 'RNA',
    Row: 3,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HIV',
    'Name of test': 'Geno',
    Row: 3,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HIV',
    'Name of test': 'TDM',
    Row: 3,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'STS',
    'Name of test': 'EIA',
    Row: 1,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'STS',
    'Name of test': 'TPPA',
    Row: 1,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'STS',
    'Name of test': 'RPR',
    Row: 2,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'STS',
    'Name of test': 'VDRL',
    Row: 2,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HAV',
    'Name of test': 'IgM',
    Row: 1,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HAV',
    'Name of test': 'IgG',
    Row: 1,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HBV',
    'Name of test': 'sAb',
    Row: 1,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HBV',
    'Name of test': 'cAb',
    Row: 1,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HBV',
    'Name of test': 'eAb',
    Row: 1,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HBV',
    'Name of test': 'sAg',
    Row: 2,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HBV',
    'Name of test': 'cAg',
    Row: 2,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HBV',
    'Name of test': 'eAg',
    Row: 2,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HBV',
    'Name of test': 'DNA',
    Row: 3,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HBV',
    'Name of test': 'Geno',
    Row: 3,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HCV',
    'Name of test': 'IgM',
    Row: 1,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HCV',
    'Name of test': 'IgG',
    Row: 1,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HCV',
    'Name of test': 'RNA',
    Row: 3,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'HCV',
    'Name of test': 'Geno',
    Row: 3,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'Other',
    'Name of test': 'Other',
    Row: 1,
  },
  {
    Section: 'BBIs',
    Category2: 'Blood-borne infections',
    Category: 'Other',
    'Name of test': 'MPV DNA',
    Row: 3,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'Urine chem',
    Category: 'Urine',
    'Name of test': 'Chem',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'Urine chem',
    Category: 'Urine',
    'Name of test': 'Other',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'Ur',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'Cr',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'eGFR',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'Na',
    Row: 2,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'K',
    Row: 2,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'ALT',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'AST',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'GGT',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'Bili',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'AFP',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'ALP',
    Row: 2,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'Alb',
    Row: 2,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'TP',
    Row: 2,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'Bone (set)',
    Category: 'LFT & Bone',
    'Name of test': 'Ca',
    Row: 3,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'Bone (set)',
    Category: 'LFT & Bone',
    'Name of test': 'Ca adj.',
    Row: 3,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'Bone (set)',
    Category: 'LFT & Bone',
    'Name of test': 'PO4',
    Row: 3,
  },
  {
    Section: 'Other Tests',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'GGT',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Hb',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'MCV',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'RBC',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'HCT',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'PCV',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'MCHb',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': '[MCHb]',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'WBC',
    Row: 2,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Neut',
    Row: 2,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Lymp',
    Row: 2,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Mono',
    Row: 2,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Baso',
    Row: 2,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Eosin',
    Row: 2,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Plats',
    Row: 3,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'Clotting (set)',
    Category: 'Haematology',
    'Name of test': 'PT',
    Row: 3,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'Clotting (set)',
    Category: 'Haematology',
    'Name of test': 'APTT',
    Row: 3,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'Clotting (set)',
    Category: 'Haematology',
    'Name of test': 'INR',
    Row: 3,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'Haematinics (set)',
    Category: 'Haematology',
    'Name of test': 'Ferr',
    Row: 4,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'Haematinics (set)',
    Category: 'Haematology',
    'Name of test': 'B12',
    Row: 4,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'Haematinics (set)',
    Category: 'Haematology',
    'Name of test': 'Fol',
    Row: 4,
  },
  {
    Section: 'Other Tests',
    Category2: 'Haematology',
    Category3: 'Haematinics (set)',
    Category: 'Haematology',
    'Name of test': 'Other',
    Row: 5,
  },
  {
    Section: 'Other Tests',
    Category2: 'Radiology',
    Category3: 'X-Ray',
    Category: 'Radiology',
    'Name of test': 'X-Ray',
    Row: 1,
  },
  {
    Section: 'Other Tests',
    Category2: 'Radiology',
    Category3: 'Ultrasound',
    Category: 'Radiology',
    'Name of test': 'USS',
    Row: 2,
  },
  {
    Section: 'Other Tests',
    Category2: 'Radiology',
    Category3: 'CT scan',
    Category: 'Radiology',
    'Name of test': 'CT',
    Row: 3,
  },
  {
    Section: 'Other Tests',
    Category2: 'Radiology',
    Category3: 'Other',
    Category: 'Radiology',
    'Name of test': 'Other',
    Row: 4,
  },
  {
    Section: 'Vaccines',
    Category2: 'Vaccines',
    Category: 'Vaccines',
    'Name of vax': 'Flu vax',
    Row: 1,
  },
  {
    Section: 'Vaccines',
    Category2: 'Vaccines',
    Category: 'Vaccines',
    'Name of vax': 'C-19 vax',
    Row: 1,
  },
  {
    Section: 'Vaccines',
    Category2: 'Vaccines',
    Category: 'Vaccines',
    'Name of vax': 'Pneumo vax',
    Row: 2,
  },
  {
    Section: 'Vaccines',
    Category2: 'Vaccines',
    Category: 'Vaccines',
    'Name of vax': 'Other vax',
    Row: 2,
  },
  {
    Section: 'Vaccines',
    Category2: 'Vaccines',
    Category: 'Vaccines',
    'Name of vax': 'HAV vax',
    Row: 1,
  },
  {
    Section: 'Vaccines',
    Category2: 'Vaccines',
    Category: 'Vaccines',
    'Name of vax': 'HBV vax',
    Row: 1,
  },
  {
    Section: 'Vaccines',
    Category2: 'Vaccines',
    Category: 'Vaccines',
    'Name of vax': 'HPV vax',
    Row: 1,
  },
  {
    Section: 'Vaccines',
    Category2: 'Vaccines',
    Category: 'Vaccines',
    'Name of vax': 'MPV vax',
    Row: 2,
  },
];
