export const other = [
  {
    Date: '30-Jun-22',
    Category2: 'Biochemistry',
    Category3: 'Urine chem',
    Category: 'Urine',
    'Name of test': 'Chem',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '3-Jul-22',
    'Lab reference': null,
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Biochemistry',
    Category3: 'Urine chem',
    Category: 'Urine',
    'Name of test': 'Chem',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '3-Oct-22',
    'Lab reference': null,
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Biochemistry',
    Category3: 'Urine chem',
    Category: 'Urine',
    'Name of test': 'Chem',
    'Result 1': 'Not reported',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'Ur',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'Ur',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'Cr',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'Cr',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'eGFR',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'eGFR',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'Na',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'Na',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'K',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Biochemistry',
    Category3: 'U&E (set)',
    Category: 'U&Es',
    'Name of test': 'K',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Hb',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Hb',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Hb',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Hb',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'MCV',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'MCV',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'MCV',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'MCV',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'RBC',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'RBC',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'RBC',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'RBC',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'HCT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'HCT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'HCT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'HCT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'PCV',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'PCV',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'PCV',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'PCV',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'MCHb',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'MCHb',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'MCHb',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'MCHb',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': '[MCHb]',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': '[MCHb]',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': '[MCHb]',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': '[MCHb]',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'WBC',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'WBC',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'WBC',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'WBC',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Neut',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Neut',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Neut',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Neut',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Lymp',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Lymp',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': 5.1,
    'Result hover': 'Reference range: 1.0 - 4.0 x109/L ',
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Lymp',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': 4.7,
    'Result hover': 'Reference range: 1.0 - 4.0 x109/L ',
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Lymp',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Mono',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Mono',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': 1.1,
    'Result hover': 'Reference range: 0.2 - 0.8 x109/L ',
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Mono',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Mono',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Baso',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Baso',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Baso',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Baso',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Eosin',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Eosin',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Eosin',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Eosin',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Plats',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Plats',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Plats',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Haematology',
    Category3: 'FBC (set)',
    Category: 'Haematology',
    'Name of test': 'Plats',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'ALP',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'ALP',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'ALP',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'ALP',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'Alb',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'Alb',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'Alb',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'Alb',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'TP',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'TP',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'TP',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'TP',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'Ca',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'Ca adj.',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jun-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'PO4',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '2-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'ALT',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': 116.0,
    'Result hover': 'Reference range: 0 - 35 U/L ',
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'ALT',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': 109.0,
    'Result hover': 'Reference range: 0 - 35 U/L ',
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'ALT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Sep-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'Bili',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '2-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'Bili',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada)',
    'Date received in lab': '7-Oct-22',
    'Date reported': '9-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '23-Dec-22',
    Category2: 'Biochemistry',
    Category3: 'LFT (set)',
    Category: 'LFT & Bone',
    'Name of test': 'Bili',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '25-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '7-Oct-22',
    Category2: 'Radiology',
    Category3: 'Ultrasound',
    Category: 'Radiology',
    'Name of test': 'USS',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Abnormal LFTs: recent diagnosis Syphilis, on PrEP (Truvada), vaxed for HAV and HBV',
    'Date received in lab': null,
    'Date reported': '12-Oct-22',
    'Lab reference': 'RadUSS23432/1',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
];
