export const STIs = [
  {
    Date: '30-Jun-20',
    Category2: 'In-clinic tests',
    Category: 'In-clinic',
    Category3: 'Urine dip',
    'Name of test': 'Urine dip',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'HCA Trish Roberts',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-20',
    Category2: 'In-clinic tests',
    Category: 'In-clinic',
    Category3: 'Preg',
    'Name of test': 'Preg',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': 'PT POSITIVE',
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'HCA Trish Roberts',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-20',
    Category2: 'STIs',
    Category: 'Throat',
    Category3: 'CT',
    'Name of test': 'Throat CT NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-20',
    'Date reported': '5-Jul-20',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-20',
    Category2: 'STIs',
    Category: 'Throat',
    Category3: 'GC',
    'Name of test': 'Throat GC NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-20',
    'Date reported': '5-Jul-20',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-20',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'CT',
    'Name of test': 'Rectal CT NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-20',
    'Date reported': '5-Jul-20',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-20',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'GC',
    'Name of test': 'Rectal GC NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-20',
    'Date reported': '5-Jul-20',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-20',
    Category2: 'STIs',
    Category: 'Uro-genital',
    Category3: 'CT',
    'Name of test': 'Uro-genital CT NAAT',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': 'DC value: 55.4',
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-20',
    'Date reported': '5-Jul-20',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-20',
    Category2: 'STIs',
    Category: 'Uro-genital',
    Category3: 'GC',
    'Name of test': 'Uro-genital GC NAAT',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': 'DC value: 76.2',
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-20',
    'Date reported': '5-Jul-20',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-22',
    Category2: 'In-clinic tests',
    Category: 'In-clinic',
    Category3: 'Urine dip',
    'Name of test': 'Urine dip',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'HCA Chris Dempster',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-22',
    Category2: 'STIs',
    Category: 'Throat',
    Category3: 'CT',
    'Name of test': 'Throat CT NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '5-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-22',
    Category2: 'STIs',
    Category: 'Throat',
    Category3: 'GC',
    'Name of test': 'Throat GC NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '5-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-22',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'CT',
    'Name of test': 'Rectal CT NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '5-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-22',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'GC',
    'Name of test': 'Rectal GC NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '5-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-22',
    Category2: 'STIs',
    Category: 'Uro-genital',
    Category3: 'CT',
    'Name of test': 'Uro-genital CT NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '5-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-22',
    Category2: 'STIs',
    Category: 'Uro-genital',
    Category3: 'GC',
    'Name of test': 'Uro-genital GC NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '5-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Jun-22',
    Category2: 'Ulcer swabs',
    Category: 'Uro-genital',
    Category3: 'HSV swab',
    'Name of test': 'Uro-genital HSV swab',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '30-Jun-22',
    'Date reported': '5-Jul-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '13-Aug-22',
    Category2: 'In-clinic tests',
    Category: 'In-clinic',
    Category3: 'Urine dip',
    'Name of test': 'Urine dip',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover':
      'SG 1.010; pH 6.5; Leu +++; Bld +; Nit ++; Ket ++; Bil neg; Uro neg; Pro ++; Glc neg ',
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'HCA Chris Dempster',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '13-Aug-22',
    Category2: 'In-clinic tests',
    Category: 'In-clinic',
    Category3: 'Microscopy',
    'Name of test': 'Microscopy',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': 'Cervical slide: PC ++; Gram neg diplococci seen',
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '13-Aug-22',
    Category2: 'Non-STI MC&S',
    Category: 'MC&S',
    Category3: 'Urine MC&S',
    'Name of test': 'Urine MC&S',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Vaginal discharge',
    'Date received in lab': '13-Aug-22',
    'Date reported': '18-Aug-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '13-Aug-22',
    Category2: 'STIs',
    Category: 'Throat',
    Category3: 'CT',
    'Name of test': 'Throat CT NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Vaginal discharge',
    'Date received in lab': '13-Aug-22',
    'Date reported': '18-Aug-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '13-Aug-22',
    Category2: 'STIs',
    Category: 'Throat',
    Category3: 'GC',
    'Name of test': 'Throat GC NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Vaginal discharge',
    'Date received in lab': '13-Aug-22',
    'Date reported': '18-Aug-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '13-Aug-22',
    Category2: 'STIs',
    Category: 'Throat',
    Category3: 'GC',
    'Name of test': 'Throat GC Culture',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Vaginal discharge',
    'Date received in lab': '13-Aug-22',
    'Date reported': '18-Aug-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '13-Aug-22',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'CT',
    'Name of test': 'Rectal CT NAAT',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': 'DC value: 32.6',
    'Clinical details': 'Vaginal discharge',
    'Date received in lab': '13-Aug-22',
    'Date reported': '18-Aug-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '13-Aug-22',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'LGV',
    'Name of test': 'Rectal LGV NAAT',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': 'Result phoned to clinic at 14:23 on 20-Aug-22',
    'Clinical details': 'Auto-added',
    'Date received in lab': '13-Aug-22',
    'Date reported': '20-Aug-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '13-Aug-22',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'GC',
    'Name of test': 'Rectal GC NAAT',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': 'DC value: 23.3',
    'Clinical details': 'Vaginal discharge',
    'Date received in lab': '13-Aug-22',
    'Date reported': '18-Aug-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '13-Aug-22',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'GC',
    'Name of test': 'Rectal GC Culture',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover':
      'Neisseria gonorrhoea isolated; RESISTANT to Doxycycline; SENSITIVE to Azithromycin, Cefixime, Ceftriaxone, Ciprofloxacin, Spectinomycin. Call ext. 4132 for further advice and guidance',
    'Clinical details': 'Vaginal discharge',
    'Date received in lab': '13-Aug-22',
    'Date reported': '18-Aug-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '13-Aug-22',
    Category2: 'STIs',
    Category: 'Uro-genital',
    Category3: 'CT',
    'Name of test': 'Uro-genital CT NAAT',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': 'DC value: 23.5',
    'Clinical details': 'Vaginal discharge',
    'Date received in lab': '13-Aug-22',
    'Date reported': '18-Aug-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '13-Aug-22',
    Category2: 'STIs',
    Category: 'Uro-genital',
    Category3: 'GC',
    'Name of test': 'Uro-genital GC NAAT',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': 'DC value: 43.2',
    'Clinical details': 'Vaginal discharge',
    'Date received in lab': '13-Aug-22',
    'Date reported': '18-Aug-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '13-Aug-22',
    Category2: 'STIs',
    Category: 'Uro-genital',
    Category3: 'GC',
    'Name of test': 'Uro-genital GC Culture',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover':
      'Neisseria gonorrhoea isolated; RESISTANT to Doxycycline; SENSITIVE to Azithromycin, Cefixime, Ceftriaxone, Ciprofloxacin, Spectinomycin. Call ext. 4132 for further advice and guidance',
    'Clinical details': 'Vaginal discharge',
    'Date received in lab': '13-Aug-22',
    'Date reported': '18-Aug-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '13-Aug-22',
    Category2: 'STIs',
    Category: 'Uro-genital',
    Category3: 'MGen',
    'Name of test': 'Uro-genital MGen NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Vaginal discharge',
    'Date received in lab': '13-Aug-22',
    'Date reported': '18-Aug-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '1-Sep-22',
    Category2: 'In-clinic tests',
    Category: 'In-clinic',
    Category3: 'Microscopy',
    'Name of test': 'Microscopy',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '1-Sep-22',
    Category2: 'STIs',
    Category: 'Throat',
    Category3: 'CT',
    'Name of test': 'Throat CT NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'GC test of cure, recent GC/CT/LGV (19 days ago)',
    'Date received in lab': '1-Sep-22',
    'Date reported': '6-Sep-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '1-Sep-22',
    Category2: 'STIs',
    Category: 'Throat',
    Category3: 'GC',
    'Name of test': 'Throat GC NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'GC test of cure, recent GC/CT/LGV (19 days ago)',
    'Date received in lab': '1-Sep-22',
    'Date reported': '6-Sep-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '1-Sep-22',
    Category2: 'STIs',
    Category: 'Throat',
    Category3: 'GC',
    'Name of test': 'Throat GC Culture',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'GC test of cure, recent GC/CT/LGV (19 days ago)',
    'Date received in lab': '1-Sep-22',
    'Date reported': '6-Sep-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '1-Sep-22',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'CT',
    'Name of test': 'Rectal CT NAAT',
    'Result 1': 'Equivocal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': 'DC value: 3.2',
    'Clinical details': 'GC test of cure, recent GC/CT/LGV (19 days ago)',
    'Date received in lab': '1-Sep-22',
    'Date reported': '6-Sep-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '1-Sep-22',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'GC',
    'Name of test': 'Rectal GC NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'GC test of cure, recent GC/CT/LGV (19 days ago)',
    'Date received in lab': '1-Sep-22',
    'Date reported': '6-Sep-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '1-Sep-22',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'GC',
    'Name of test': 'Rectal GC Culture',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'GC test of cure, recent GC/CT/LGV (19 days ago)',
    'Date received in lab': '1-Sep-22',
    'Date reported': '6-Sep-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '1-Sep-22',
    Category2: 'STIs',
    Category: 'Uro-genital',
    Category3: 'CT',
    'Name of test': 'Uro-genital CT NAAT',
    'Result 1': 'Equivocal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': 'DC value: 1.2',
    'Clinical details': 'GC test of cure, recent GC/CT/LGV (19 days ago)',
    'Date received in lab': '1-Sep-22',
    'Date reported': '6-Sep-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '1-Sep-22',
    Category2: 'STIs',
    Category: 'Uro-genital',
    Category3: 'GC',
    'Name of test': 'Uro-genital GC NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'GC test of cure, recent GC/CT/LGV (19 days ago)',
    'Date received in lab': '1-Sep-22',
    'Date reported': '6-Sep-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '1-Sep-22',
    Category2: 'STIs',
    Category: 'Uro-genital',
    Category3: 'GC',
    'Name of test': 'Uro-genital GC Culture',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'GC test of cure, recent GC/CT/LGV (19 days ago)',
    'Date received in lab': '1-Sep-22',
    'Date reported': '6-Sep-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Sep-22',
    Category2: 'In-clinic tests',
    Category: 'In-clinic',
    Category3: 'Urine dip',
    'Name of test': 'Urine dip',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'HCA Trish Roberts',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Sep-22',
    Category2: 'STIs',
    Category: 'Throat',
    Category3: 'CT',
    'Name of test': 'Throat CT NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Unwell, genital ulceration, on PrEP, recent throat and rectal GC and LGV (August 2022)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '5-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Sep-22',
    Category2: 'STIs',
    Category: 'Throat',
    Category3: 'GC',
    'Name of test': 'Throat GC NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Unwell, genital ulceration, on PrEP, recent throat and rectal GC and LGV (August 2022)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '5-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Sep-22',
    Category2: 'Ulcer swabs',
    Category: 'Throat',
    Category3: 'MPV swab',
    'Name of test': 'Throat MPV swab',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Unwell, genital ulceration, on PrEP, recent throat and rectal GC and LGV (August 2022)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '5-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Sep-22',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'CT',
    'Name of test': 'Rectal CT NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Unwell, genital ulceration, on PrEP, recent throat and rectal GC and LGV (August 2022)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '5-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Sep-22',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'GC',
    'Name of test': 'Rectal GC NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Unwell, genital ulceration, on PrEP, recent throat and rectal GC and LGV (August 2022)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '5-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Sep-22',
    Category2: 'STIs',
    Category: 'Uro-genital',
    Category3: 'CT',
    'Name of test': 'Uro-genital CT NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Unwell, genital ulceration, on PrEP, recent throat and rectal GC and LGV (August 2022)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '5-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Sep-22',
    Category2: 'STIs',
    Category: 'Uro-genital',
    Category3: 'GC',
    'Name of test': 'Uro-genital GC NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Unwell, genital ulceration, on PrEP, recent throat and rectal GC and LGV (August 2022)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '5-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Sep-22',
    Category2: 'Ulcer swabs',
    Category: 'Uro-genital',
    Category3: 'HSV swab',
    'Name of test': 'Uro-genital HSV swab',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Unwell, genital ulceration, on PrEP, recent throat and rectal GC and LGV (August 2022)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '5-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Sep-22',
    Category2: 'Ulcer swabs',
    Category: 'Uro-genital',
    Category3: 'Syphilis swab',
    'Name of test': 'Uro-genital Syphilis swab',
    'Result 1': 'Abnormal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Unwell, genital ulceration, on PrEP, recent throat and rectal GC and LGV (August 2022)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '5-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '30-Sep-22',
    Category2: 'Ulcer swabs',
    Category: 'Uro-genital',
    Category3: 'MPV swab',
    'Name of test': 'Uro-genital MPV swab',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details':
      'Unwell, genital ulceration, on PrEP, recent throat and rectal GC and LGV (August 2022)',
    'Date received in lab': '30-Sep-22',
    'Date reported': '5-Oct-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '23-Dec-22',
    Category2: 'In-clinic tests',
    Category: 'In-clinic',
    Category3: 'Urine dip',
    'Name of test': 'Urine dip',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'HCA Chris Dempster',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '23-Dec-22',
    Category2: 'STIs',
    Category: 'Throat',
    Category3: 'CT',
    'Name of test': 'Throat CT NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '28-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Main',
  },
  {
    Date: '23-Dec-22',
    Category2: 'STIs',
    Category: 'Throat',
    Category3: 'GC',
    'Name of test': 'Throat GC NAAT',
    'Result 1': 'Not reported',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': null,
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Shaw',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '23-Dec-22',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'CT',
    'Name of test': 'Rectal CT NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '28-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '23-Dec-22',
    Category2: 'STIs',
    Category: 'Rectal',
    Category3: 'GC',
    'Name of test': 'Rectal GC NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Screen (on PrEP)',
    'Date received in lab': '23-Dec-22',
    'Date reported': '28-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
  {
    Date: '23-Dec-22',
    Category2: 'STIs',
    Category: 'Uro-genital',
    Category3: 'CT',
    'Name of test': 'Uro-genital CT NAAT',
    'Result 1': 'Normal',
    'Result 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Result hover': null,
    'Clinical details': 'Routine Screen (on PrEP), on PrEP',
    'Date received in lab': '23-Dec-22',
    'Date reported': '28-Dec-22',
    'Lab reference': 'GUMxxyyzz',
    Clinician: 'Dr Pao',
    'Clinic location': 'Dartmoor clinic',
  },
];
