export const vaccines = [
  {
    Date: '7-Oct-22',
    'Date due start': null,
    'Date due end': null,
    'Name of vax': 'Flu vax',
    'Status 1': 'Due, Administered or Missed',
    'Status 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'GP',
    'Clinic location': 'Dousland Surgery',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '14-Dec-20',
    'Date due start': null,
    'Date due end': null,
    'Name of vax': 'C-19 vax',
    'Status 1': 'Due, Administered or Missed',
    'Status 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: null,
    'Clinic location': 'NHS',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '14-Mar-21',
    'Date due start': '11-Jan-21',
    'Date due end': '14-Jun-21',
    'Name of vax': 'C-19 vax',
    'Status 1': 'Due, Administered or Missed',
    'Status 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: null,
    'Clinic location': 'NHS',
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: null,
    'Date due start': '14-Mar-22',
    'Date due end': '14-Sep-22',
    'Name of vax': 'C-19 vax',
    'Status 1': 'Due, Administered or Missed',
    'Status 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Status hover':
      'Patient reports that they no longer wish to receive C-19 vaccines as concerns for safety',
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: null,
    'Clinic location': null,
    Brand: null,
    Dose: null,
    Site: null,
    'Batch number': null,
    'Expiry date': null,
  },
  {
    Date: '30-Jan-22',
    'Date due start': null,
    'Date due end': null,
    'Name of vax': 'HAV vax',
    'Status 1': 'Due, Administered or Missed',
    'Status 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Mitchell',
    'Clinic location': 'Dartmoor clinic',
    Brand: 'Havrix ',
    Dose: '1mL',
    Site: 'Left deltoid IM',
    'Batch number': 'V/Rrcxxyyzz',
    'Expiry date': 'Feb-25',
  },
  {
    Date: '30-Jun-22',
    'Date due start': '30-May-22',
    'Date due end': '30-Jan-23',
    'Name of vax': 'HAV vax',
    'Status 1': 'Due, Administered or Missed',
    'Status 2': null,
    'Timeline static': 'CC',
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Mitchell',
    'Clinic location': 'Dartmoor clinic',
    Brand: 'Havrix ',
    Dose: '1mL',
    Site: 'Left deltoid IM',
    'Batch number': 'V/Rrcxxyyzz',
    'Expiry date': 'Feb-25',
  },
  {
    Date: '30-Jan-22',
    'Date due start': null,
    'Date due end': null,
    'Name of vax': 'HBV vax',
    'Status 1': 'Due, Administered or Missed',
    'Status 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Mitchell',
    'Clinic location': 'Dartmoor clinic',
    Brand: 'Engerix B',
    Dose: '20mcg',
    Site: 'Right deltoid IM',
    'Batch number': 'V/Rrcxxyyzz',
    'Expiry date': 'Jun-25',
  },
  {
    Date: '1-Mar-22',
    'Date due start': '27-Feb-22',
    'Date due end': '27-Mar-22',
    'Name of vax': 'HBV vax',
    'Status 1': 'Due, Administered or Missed',
    'Status 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Mitchell',
    'Clinic location': 'Dartmoor clinic',
    Brand: 'Engerix B',
    Dose: '20mcg',
    Site: 'Right deltoid IM',
    'Batch number': 'V/Rrcxxyyzz',
    'Expiry date': 'Jul-25',
  },
  {
    Date: '29-Jul-22',
    'Date due start': '30-May-22',
    'Date due end': '30-Jan-24',
    'Name of vax': 'HBV vax',
    'Status 1': 'Due, Administered or Missed',
    'Status 2': null,
    'Timeline static': 'CC',
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Mitchell',
    'Clinic location': 'Dartmoor clinic',
    Brand: 'Engerix B',
    Dose: '20mcg',
    Site: 'Right deltoid IM',
    'Batch number': 'V/Rrcxxyyzz',
    'Expiry date': 'Nov-25',
  },
  {
    Date: '7-Oct-22',
    'Date due start': null,
    'Date due end': null,
    'Name of vax': 'HBV vax',
    'Status 1': 'Due, Administered or Missed',
    'Status 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Status hover': null,
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Mitchell',
    'Clinic location': 'Dartmoor clinic',
    Brand: 'Engerix B',
    Dose: '20mcg',
    Site: 'Right deltoid IM',
    'Batch number': 'V/Rrcxxyyzz',
    'Expiry date': 'Nov-25',
  },
  {
    Date: '30-Jan-22',
    'Date due start': '30-Jul-22',
    'Date due end': '30-Jan-24',
    'Name of vax': 'HPV vax',
    'Status 1': 'Due, Administered or Missed',
    'Status 2': null,
    'Timeline static': null,
    'Episode static': null,
    'Status hover': 'Pt reports very painful immediately after injection',
    'Clinical details': null,
    'Date received in lab': null,
    'Date reported': null,
    'Lab reference': null,
    Clinician: 'Dr Mitchell',
    'Clinic location': 'Dartmoor clinic',
    Brand: 'Gardasil 9',
    Dose: '0.5mL',
    Site: 'Right deltoid IM',
    'Batch number': 'V/Rrcxxyyzz',
    'Expiry date': 'Jan-26',
  }
];
